CREATE TABLE `OtherIdentifierType` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` char(3) COLLATE utf8_unicode_ci NOT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `lang_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `OtherIdentifierType` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES 
(NULL, 'A1', 'Reporting Organisation’s internal activity identifier', '', '1'),
(NULL, 'A2', 'CRS Activity identifier', '', '1'),
(NULL, 'A3', 'Previous Activity Identifier', 'The standard insists that once an activity has been reported to IATI its identifier MUST NOT be changed, even if the reporting organisation changes its organisation identifier. There may be exceptional circumstances in which this rule cannot be followed, in which case the previous identifier should be reported using this code.', '1'),
(NULL, 'A9', 'Other Activity Identifier', '', '1'),
(NULL, 'B1', 'Previous Reporting Organisation Identifier', '', '1'),
(NULL, 'B9', 'Other Organisation Identifier', '', '1'),
(NULL, 'A1', 'Reporting Organisation’s internal activity identifier', '', '2'),
(NULL, 'A2', 'CRS Activity identifier', '', '2'),
(NULL, 'A3', 'Previous Activity Identifier', 'The standard insists that once an activity has been reported to IATI its identifier MUST NOT be changed, even if the reporting organisation changes its organisation identifier. There may be exceptional circumstances in which this rule cannot be followed, in which case the previous identifier should be reported using this code.', '2'),
(NULL, 'A9', 'Other Activity Identifier', '', '2'),
(NULL, 'B1', 'Previous Reporting Organisation Identifier', '', '2'),
(NULL, 'B9', 'Other Organisation Identifier', '', '2'),
(NULL, 'A1', 'Reporting Organisation’s internal activity identifier', '', '3'),
(NULL, 'A2', 'CRS Activity identifier', '', '3'),
(NULL, 'A3', 'Previous Activity Identifier', 'The standard insists that once an activity has been reported to IATI its identifier MUST NOT be changed, even if the reporting organisation changes its organisation identifier. There may be exceptional circumstances in which this rule cannot be followed, in which case the previous identifier should be reported using this code.', '3'),
(NULL, 'A9', 'Other Activity Identifier', '', '3'),
(NULL, 'B1', 'Previous Reporting Organisation Identifier', '', '3'),
(NULL, 'B9', 'Other Organisation Identifier', '', '3');


CREATE TABLE `SectorVocabulary` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lang_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `SectorVocabulary` (`id`, `Code`, `Name`, `lang_id`) VALUES 
(1, '1', 'AidData', '1'),
(2, '2', 'Classification of the Functions of Government (UN)', '1'),
(3, '3', 'OECD Development Assistance Committee', '1'),
(4, '5', 'International Organization for Standardization', '1'),
(5, '7', 'National Taxonomy for Exempt Entities (USA)', '1'),
(6, '99', 'Reporting Organisation (i.e. maintained by the organisation referred to in the <reporting-org> element.', '1'),
(7, '8', 'World Bank', '1'),
(8, '4', 'OECD Development Assistance Committee 3 digit codes', '1'),
(9, '6', 'Statistical classification of economic activities in the European Community', '1'),
(10, '1', 'AidData', '2'),
(11, '2', 'Classification of the Functions of Government (UN)', '2'),
(12, '3', 'OECD Development Assistance Committee', '2'),
(13, '5', 'International Organization for Standardization', '2'),
(14, '7', 'National Taxonomy for Exempt Entities (USA)', '2'),
(15, '99', 'Reporting Organisation (i.e. maintained by the organisation referred to in the <reporting-org> element.', '2'),
(16, '8', 'World Bank', '2'),
(17, '4', 'OECD Development Assistance Committee 3 digit codes', '2'),
(18, '6', 'Statistical classification of economic activities in the European Community', '2'),
(19, '1', 'AidData', '3'),
(20, '2', 'Classification of the Functions of Government (UN)', '3'),
(21, '3', 'OECD Development Assistance Committee', '3'),
(22, '5', 'International Organization for Standardization', '3'),
(23, '7', 'National Taxonomy for Exempt Entities (USA)', '3'),
(24, '99', 'Reporting Organisation (i.e. maintained by the organisation referred to in the <reporting-org> element.', '3'),
(25, '8', 'World Bank', '3'),
(26, '4', 'OECD Development Assistance Committee 3 digit codes', '3'),
(27, '6', 'Statistical classification of economic activities in the European Community', '3');


CREATE TABLE `PolicyMarkerVocabulary` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lang_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `PolicyMarkerVocabulary` (`id`, `Code`, `Name`, `lang_id`) VALUES 
(NULL, '1', 'OECD Development Assistance Committee', '1'),
(NULL, '99', 'Reporting Organisation (i.e. maintained by the organisation referred to in the <reporting-org> element.', '1'),
(NULL, '1', 'OECD Development Assistance Committee', '2'),
(NULL, '99', 'Reporting Organisation (i.e. maintained by the organisation referred to in the <reporting-org> element.', '2'),
(NULL, '1', 'OECD Development Assistance Committee', '3'),
(NULL, '99', 'Reporting Organisation (i.e. maintained by the organisation referred to in the <reporting-org> element.', '3');


CREATE TABLE `Version` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` float DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` mediumtext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `Version` (`id`, `Code`, `Name`, `Description`) VALUES 
(NULL, '1.01', '', ''),
(NULL, '1.02', 'CRS Activity identifier', ''),
(NULL, '1.03', '', ''),
(NULL, '1.04', '', ''),
(NULL, '1.05', '', ''),
(NULL, '2.01', '', '');


INSERT INTO `DocumentCategory` (`id`, `Code`, `Name`, `CategoryCode`, `lang_id`) VALUES
(75, 'A12', 'Activity web page', 'A', '1'),
(76, 'A12', 'Activity web page', 'A', '2'),
(77, 'A12', 'Activity web page', 'A', '3'),
(78, 'B16', 'Organisation web page', 'B', '1'),
(79, 'B16', 'Organisation web page', 'B', '2'),
(80, 'B16', 'Organisation web page', 'B', '3'),
(81, 'B17', 'Country/Region web page', 'B', '1'),
(82, 'B17', 'Country/Region web page', 'B', '2'),
(83, 'B17', 'Country/Region web page', 'B', '3'),
(84, 'B18', 'Sector web page', 'B', '1'),
(85, 'B18', 'Sector web page', 'B', '2'),
(86, 'B18', 'Sector web page', 'B', '3');


UPDATE `ActivityDateType` SET Code= 1 WHERE Code='start-planned';
UPDATE `ActivityDateType` SET Code= 2 WHERE Code='start-actual';
UPDATE `ActivityDateType` SET Code= 3 WHERE Code='end-planned';
UPDATE `ActivityDateType` SET Code= 4 WHERE Code='end-actual';


UPDATE `GazetteerAgency` SET Code= 1 WHERE Code='GEO';
UPDATE `GazetteerAgency` SET Code= 2 WHERE Code='NGA';
UPDATE `GazetteerAgency` SET Code= 3 WHERE Code='OSM';


UPDATE `OrganisationRole` SET Code= 1 WHERE Code='Funding';
UPDATE `OrganisationRole` SET Code= 2 WHERE Code='Accountable';
UPDATE `OrganisationRole` SET Code= 3 WHERE Code='Extending';
UPDATE `OrganisationRole` SET Code= 4 WHERE Code='Implementing';


UPDATE `TransactionType` SET Code= 1 WHERE Code='IF';
UPDATE `TransactionType` SET Code= 2 WHERE Code='C';
UPDATE `TransactionType` SET Code= 3 WHERE Code='D';
UPDATE `TransactionType` SET Code= 4 WHERE Code='E';
UPDATE `TransactionType` SET Code= 5 WHERE Code='IR';
UPDATE `TransactionType` SET Code= 6 WHERE Code='LR';
UPDATE `TransactionType` SET Code= 7 WHERE Code='R';
UPDATE `TransactionType` SET Code= 8 WHERE Code='QP';
UPDATE `TransactionType` SET Code= 9 WHERE Code='QS';
UPDATE `TransactionType` SET Code= 10 WHERE Code='CG';


CREATE TABLE `GeographicVocabulary` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`Code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
`Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
`Description` mediumtext COLLATE utf8_unicode_ci,
`lang_id` int(11) NOT NULL DEFAULT '1',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `GeographicVocabulary` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES
(NULL, 'A1', 'Global Admininistrative Unit Layers', '', '1'),
(NULL, 'A2', 'UN Second Administrative Level Boundary Project','Note: the unsalb.org website is no longer accessible, and public access to the bou
ndaries resources has been removed http://www.ungiwg.org/content/united-nations-international-and-administrative-boundaries-resources', '1'),
(NULL, 'A3', 'Global Administrative Areas', '', '1'),
(NULL, 'A4', 'ISO Country (3166-1 alpha-2)', '', '1'),
(NULL, 'G1', 'Geonames', '', '1'),
(NULL, 'G2', 'OpenStreetMap', 'Note: the code should be formed by prefixing the relevant OpenStreetMap ID with node/ way/ or relation/ as appropriate, e.g. node/1234567', '1'),
(NULL, 'A1', 'Global Admininistrative Unit Layers', '', '2'),
(NULL, 'A2', 'UN Second Administrative Level Boundary Project','Note: the unsalb.org website is no longer accessible, and public access to the boundaries resources has been removed http://www.ungiwg.org/content/united-nations-international-and-administrative-boundaries-resources', '2'),
(NULL, 'A3', 'Global Administrative Areas', '', '2'),
(NULL, 'A4', 'ISO Country (3166-1 alpha-2)', '', '2'),
(NULL, 'G1', 'Geonames', '', '2'),
(NULL, 'G2', 'OpenStreetMap', 'Note: the code should be formed by prefixing the relevant OpenStreetMap ID with node/ way/ or relation/ as appropriate, e.g. node/1234567', '2'),
(NULL, 'A1', 'Global Admininistrative Unit Layers', '', '3'),
(NULL, 'A2', 'UN Second Administrative Level Boundary Project','Note: the unsalb.org website is no longer accessible, and public access to the boundaries resources has been removed http://www.ungiwg.org/content/united-nations-international-and-administrative-boundaries-resources', '3'),
(NULL, 'A3', 'Global Administrative Areas', '', '3'),
(NULL, 'A4', 'ISO Country (3166-1 alpha-2)', '', '3'),
(NULL, 'G1', 'Geonames', '', '3'),
(NULL, 'G2', 'OpenStreetMap', 'Note: the code should be formed by prefixing the relevant OpenStreetMap ID with node/ way/ or relation/ as appropriate, e.g. node/1234567', '3');


CREATE TABLE `GeographicLocationReach` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `lang_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `GeographicLocationReach` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES 
(NULL, '1', 'Activity', 'The location specifies where the activity is carried out.', '1'),
(NULL, '2', 'Intended Beneficiaries.','The location specifies where the intended beneficiaries of the activity live', '1'),
(NULL, '1', 'Activity', 'The location speci
fies where the activity is carried out.', '2'),
(NULL, '2', 'Intended Beneficiaries.','The location specifies where the intended beneficiaries of the activity live', '2'),
(NULL, '1', 'Activity', 'The location specifies where the activity is carried out.', '3'),
(NULL, '2', 'Intended Beneficiaries.','The location specifies where the intended beneficiaries of the activity live', '3');


CREATE TABLE `GeographicExactness` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` mediumtext COLLATE utf8_unicode_ci,
  `lang_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `GeographicExactness` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES 
(NULL, '1', 'Exact', 'The designated geographic location is exact.', '1'),
(NULL, '2', 'Approximate', 'The designated geographic location is approximate.', '1'),
(NULL, '1', 'Exact', 'The designated geographic location is exact.', '2'),
(NULL, '2', 'Approximate', 'The designated geographic location is approximate.', '2'),
(NULL, '1', 'Exact', 'The designated geographic location is exact.', '3'),
(NULL, '2', 'Approximate', 'The designated geographic location is approximate.', '3');


CREATE TABLE `GeographicLocationClass` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `lang_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO `GeographicLocationClass` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES 
(NULL, '1', 'Administrative Region', 'The designated geographic location is an administrative region (state, county, province, district, municipality etc.)', '1'),
(NULL, '2', 'Populated Place','The designated geographic location is a populated place (town, vill
age, farm etc.)', '1'),
(NULL, '3', 'Structure', 'The designated geopgraphic location is a structure (such as a school or a clinic)', '1'),
(NULL, '4', 'Other Topographical Feature', 'The designated geographic location is a topographical feature, such as a mountain, a river, a forest', '1'),
(NULL, '1', 'Administrative Region', 'The designated geographic location is an administrative region (state, county, province, district, municipality etc.)', '2'),
(NULL, '2', 'Populated Place','The designated geographic location is a populated place (town, village, farm etc.)', '2'),
(NULL, '3', 'Structure', 'The designated geopgraphic location is a structure (such as a school or a clinic)', '2'),
(NULL, '4', 'Other Topographical Feature', 'The designated geographic location is a topographical feature, such as a mountain, a river, a forest', '2'),
(NULL, '1', 'Administrative Region', 'The designated geographic location is an administrative region (state, county, province, district, municipality etc.)', '3'),
(NULL, '2', 'Populated Place','The designated geographic location is a populated place (town, village, farm etc.)', '3'),
(NULL, '3', 'Structure', 'The designated geopgraphic location is a structure (such as a school or a clinic)', '3'),
(NULL, '4', 'Other Topographical Feature', 'The designated geographic location is a topographical feature, such as a mountain, a river, a forest', '3');


CREATE TABLE `ContactType` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` int(11) NOT NULL,
  `Name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lang_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `ContactType` (`id` ,`Code` ,`Name` ,`lang_id`) VALUES 
(NULL, 1, 'General Enquiries', 1),
(NULL, 2, 'Project Management', 1),
(NULL, 3, 'Financial Management', 1),
(NULL, 4, 'Communications', 1),
(NULL, 1, 'General Enquiries', 2),
(NULL, 2, 'Project Management', 2),
(NULL, 3, 'Financial Management', 2),
(NULL, 4, 'Communications', 2),
(NULL, 1, 'General Enquiries', 3),
(NULL, 2, 'Project Management', 3),
(NULL, 3, 'Financial Management', 3),
(NULL, 4, 'Communications', 3);

ALTER TABLE  `iati_contact_info` CHANGE  `@type`  `text` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL ;

ALTER TABLE  `iati_contact_info` ADD  `@type` VARCHAR( 255 ) DEFAULT NULL AFTER  `activity_id` ;

RENAME TABLE `LocationType` TO `LocationTypeOld`;

CREATE TABLE IF NOT EXISTS `LocationType` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `Name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `lang_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `LocationType` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES
(1, 'AIRQ', 'abandoned airfield', 'abandoned airfield', 1),
(2, 'CMPQ', 'abandoned camp', 'abandoned camp', 1),
(3, 'CNLQ', 'abandoned canal', 'abandoned canal', 1),
(4, 'MFGQ', 'abandoned factory', 'abandoned factory', 1),
(5, 'FRMQ', 'abandoned farm', 'abandoned farm', 1),
(6, 'MNQ', 'abandoned mine', 'abandoned mine', 1),
(7, 'MSSNQ', 'abandoned mission', 'abandoned mission', 1),
(8, 'OILQ', 'abandoned oil well', 'abandoned oil well', 1),
(9, 'PPQ', 'abandoned police post', 'abandoned police post', 1),
(10, 'PPLQ', 'abandoned populated place', 'abandoned populated place', 1),
(11, 'PRNQ', 'abandoned prison', 'abandoned prison', 1),
(12, 'RRQ', 'abandoned railroad', 'abandoned railroad', 1),
(13, 'RSTNQ', 'abandoned railroad station', 'abandoned railroad station', 1),
(14, 'RSTPQ', 'abandoned railroad stop', 'abandoned railroad stop', 1),
(15, 'STMQ', 'abandoned watercourse', 'a former stream or distributary no longer carrying flowing water, but still evident due to lakes, wetland, topographic or vegetation patterns', 1),
(16, 'WLLQ', 'abandoned well', 'abandoned well', 1),
(17, 'ADMD', 'administrative division', 'an administrative division of a political entity, undifferentiated as to administrative level', 1),
(18, 'ADMF', 'administrative facility', 'a government building', 1),
(19, 'AGRC', 'agricultural colony', 'a tract of land set aside for agricultural settlement', 1),
(20, 'AGRF', 'agricultural facility', 'a building and/or tract of land used for improving agriculture', 1),
(21, 'RESA', 'agricultural reserve', 'a tract of land reserved for agricultural reclamation and/or development', 1),
(22, 'SCHA', 'agricultural school', 'a school with a curriculum focused on agriculture', 1),
(23, 'AIRB', 'airbase', 'an area used to store supplies, provide barracks for air force personnel, hangars and runways for aircraft, and from which operations are initiated', 1),
(24, 'AIRF', 'airfield', 'a place on land where aircraft land and take off; no facilities provided for the commercial handling of passengers and cargo', 1),
(25, 'AIRP', 'airport', 'a place where aircraft regularly land and take off, with runways, navigational aids, and major facilities for the commercial handling of passengers and cargo', 1),
(26, 'AMTH', 'amphitheater', 'an oval or circular structure with rising tiers of seats about a stage or open space', 1),
(27, 'STMA', 'anabranch', 'a diverging branch flowing out of a main stream and rejoining it downstream', 1),
(28, 'ANCH', 'anchorage', 'an area where vessels may anchor', 1),
(29, 'RDA', 'ancient road', 'the remains of a road used by ancient cultures', 1),
(30, 'ANS', 'ancient site', 'a place where archeological remains, old structures, or cultural artifacts are located', 1),
(31, 'WALLA', 'ancient wall', 'the remains of a linear defensive stone structure', 1),
(32, 'BLDA', 'apartment building', 'a building containing several individual apartments', 1),
(33, 'AQC', 'aquaculture facility', 'facility or area for the cultivation of aquatic animals and plants, especially fish, shellfish, and seaweed, in natural or controlled marine or freshwater environments; underwater agriculture', 1),
(34, 'CNLA', 'aqueduct', 'a conduit used to carry water', 1),
(35, 'ARCH', 'arch', 'a natural or man-made structure in the form of an arch', 1),
(36, 'LAND', 'Arctic land', 'a tract of land in the Arctic', 1),
(37, 'AREA', 'area', 'a tract of land without homogeneous character or boundaries', 1),
(38, 'ISLF', 'artificial island', 'an island created by landfill or diking and filling in a wetland, bay, or lagoon', 1),
(39, 'RNGA', 'artillery range', 'a tract of land used for artillery firing practice', 1),
(40, 'ASPH', 'asphalt lake', 'a small basin containing naturally occurring asphalt', 1),
(41, 'ASTR', 'astronomical station', 'a point on the earth whose position has been determined by observations of celestial bodies', 1),
(42, 'ASYL', 'asylum', 'a facility where the insane are cared for and protected', 1),
(43, 'ATHF', 'athletic field', 'a tract of land used for playing team sports, and athletic track and field events', 1),
(44, 'ATOL', 'atoll(s)', 'a ring-shaped coral reef which has closely spaced islands on it encircling a lagoon', 1),
(45, 'CTRA', 'atomic center', 'a facility where atomic research is carried out', 1),
(46, 'BDLD', 'badlands', 'an area characterized by a maze of very closely spaced, deep, narrow, steep-sided ravines, and sharp crests and pinnacles', 1),
(47, 'BSTN', 'baling station', 'a facility for baling agricultural products', 1),
(48, 'ESTB', 'banana plantation', 'an estate that specializes in the growing of bananas', 1),
(49, 'BAN', 'bank', 'an establishment for the custody, loan, exchange or issue of money, for the extension of credit, and for facilitating the transmission of funds', 1),
(50, 'BNK', 'bank(s)', 'an elevation, typically located on a shelf, over which the depth of water is relatively shallow but sufficient for most surface navigation', 1),
(51, 'BAR', 'bar', 'a shallow ridge or mound of coarse unconsolidated material in a stream channel, at the mouth of a stream, estuary, or lagoon and in the wave-break zone along coasts', 1),
(52, 'BRKS', 'barracks', 'a building for lodging military personnel', 1),
(53, 'BTL', 'battlefield', 'a site of a land battle of historical importance', 1),
(54, 'BAY', 'bay', 'a coastal indentation between two capes or headlands, larger than a cove but smaller than a gulf', 1),
(55, 'BAYS', 'bays', 'coastal indentations between two capes or headlands, larger than a cove but smaller than a gulf', 1),
(56, 'BCH', 'beach', 'a shore zone of coarse unconsolidated sediment that extends from the low-water line to the highest reach of storm waves', 1),
(57, 'RDGB', 'beach ridge', 'a ridge of sand just inland and parallel to the beach, usually in series', 1),
(58, 'BCHS', 'beaches', 'a shore zone of coarse unconsolidated sediment that extends from the low-water line to the highest reach of storm waves', 1),
(59, 'BCN', 'beacon', 'a fixed artificial navigation mark', 1),
(60, 'BNCH', 'bench', 'a long, narrow bedrock platform bounded by steeper slopes above and below, usually overlooking a waterbody', 1),
(61, 'BGHT', 'bight(s)', 'an open body of water forming a slight recession in a coastline', 1),
(62, 'BLHL', 'blowhole(s)', 'a hole in coastal rock through which sea water is forced by a rising tide or waves and spurted through an outlet into the air', 1),
(63, 'BLOW', 'blowout(s)', 'a small depression in sandy terrain, caused by wind erosion', 1),
(64, 'BTYD', 'boatyard', 'a waterside facility for servicing, repairing, and building small vessels', 1),
(65, 'BOG', 'bog(s)', 'a wetland characterized by peat forming sphagnum moss, sedge, and other acid-water plants', 1),
(66, 'PSTB', 'border post', 'a post or station at an international boundary for the regulation of movement of people and goods', 1),
(67, 'BLDR', 'boulder field', 'a high altitude or high latitude bare, flat area covered with large angular rocks', 1),
(68, 'BP', 'boundary marker', 'a fixture marking a point along a boundary', 1),
(69, 'BRKW', 'breakwater', 'a structure erected to break the force of waves at the entrance to a harbor or port', 1),
(70, 'MFGB', 'brewery', 'one or more buildings where beer is brewed', 1),
(71, 'BDG', 'bridge', 'a structure erected across an obstacle such as a stream, road, etc., in order to carry roads, railroads, and pedestrians across', 1),
(72, 'ZNB', 'buffer zone', 'a zone recognized as a buffer between two nations in which military presence is minimal or absent', 1),
(73, 'BLDG', 'building(s)', 'a structure built for permanent use, as a house, factory, etc.', 1),
(74, 'BUR', 'burial cave(s)', 'a cave used for human burials', 1),
(75, 'BUSH', 'bush(es)', 'a small clump of conspicuous bushes in an otherwise bare area', 1),
(76, 'CTRB', 'business center', 'a place where a number of businesses are located', 1),
(77, 'BUTE', 'butte(s)', 'a small, isolated, usually flat-topped hill with steep sides', 1),
(78, 'CARN', 'cairn', 'a heap of stones erected as a landmark or for other purposes', 1),
(79, 'CLDA', 'caldera', 'a depression measuring kilometers across formed by the collapse of a volcanic mountain', 1),
(80, 'CMP', 'camp(s)', 'a site occupied by tents, huts, or other shelters for temporary use', 1),
(81, 'CNL', 'canal', 'an artificial watercourse', 1),
(82, 'CNLB', 'canal bend', 'a conspicuously curved or bent section of a canal', 1),
(83, 'TNLC', 'canal tunnel', 'a tunnel through which a canal passes', 1),
(84, 'STMC', 'canalized stream', 'a stream that has been substantially ditched, diked, or straightened', 1),
(85, 'MFGC', 'cannery', 'a building where food items are canned', 1),
(86, 'CNYN', 'canyon', 'a deep, narrow valley with steep sides cutting into a plateau or mountainous area', 1),
(87, 'CAPE', 'cape', 'a land area, more prominent than a point, projecting into the sea and marking a notable change in coastal direction', 1),
(88, 'PPLC', 'capital of a political entity', 'capital of a political entity', 1),
(89, 'RTE', 'caravan route', 'the route taken by caravans', 1),
(90, 'CSNO', 'casino', 'a building used for entertainment, especially gambling', 1),
(91, 'CSTL', 'castle', 'a large fortified building or set of buildings', 1),
(92, 'TNKD', 'cattle dipping tank', 'a small artificial pond used for immersing cattle in chemically treated water for disease control', 1),
(93, 'CSWY', 'causeway', 'a raised roadway across wet ground or shallow water', 1),
(94, 'CAVE', 'cave(s)', 'an underground passageway or chamber, or cavity on the side of a cliff', 1),
(95, 'CMTY', 'cemetery', 'a burial place or ground', 1),
(96, 'CHN', 'channel', 'the deepest part of a stream, bay, lagoon, or strait, through which the main current flows', 1),
(97, 'MNCR', 'chrome mine(s)', 'a mine where chrome ore is extracted', 1),
(98, 'CH', 'church', 'a building for public Christian worship', 1),
(99, 'CRQ', 'cirque', 'a bowl-like hollow partially surrounded by cliffs or steep slopes at the head of a glaciated valley', 1),
(100, 'CRQS', 'cirques', 'bowl-like hollows partially surrounded by cliffs or steep slopes at the head of a glaciated valley', 1),
(101, 'CLG', 'clearing', 'an area in a forest with trees removed', 1),
(102, 'CFT', 'cleft(s)', 'a deep narrow slot, notch, or groove in a coastal cliff', 1),
(103, 'CLF', 'cliff(s)', 'a high, steep to perpendicular slope overlooking a waterbody or lower area', 1),
(104, 'HSPC', 'clinic', 'a medical facility associated with a hospital for outpatients', 1),
(105, 'MNC', 'coal mine(s)', 'a mine where coal is extracted', 1),
(106, 'COLF', 'coalfield', 'a region in which coal deposits of possible economic value occur', 1),
(107, 'CST', 'coast', 'a zone of variable width straddling the shoreline', 1),
(108, 'STNC', 'coast guard station', 'a facility from which the coast is guarded by armed vessels', 1),
(109, 'GRVC', 'coconut grove', 'a planting of coconut trees', 1),
(110, 'SCHC', 'college', 'the grounds and buildings of an institution of higher learning', 1),
(111, 'CMN', 'common', 'a park or pasture for community use', 1),
(112, 'COMC', 'communication center', 'a facility, including buildings, antennae, towers and electronic equipment for receiving and transmitting information', 1),
(113, 'CTRCM', 'community center', 'a facility for community recreation and other activities', 1),
(114, 'CNS', 'concession area', 'a lease of land by a government for economic development, e.g., mining, forestry', 1),
(115, 'CONE', 'cone(s)', 'a conical landform composed of mud or volcanic material', 1),
(116, 'CNFL', 'confluence', 'a place where two or more streams or intermittent streams flow together', 1),
(117, 'CRSU', 'continental rise', 'a gentle slope rising from oceanic depths towards the foot of a continental slope', 1),
(118, 'CVNT', 'convent', 'a building where a community of nuns lives in seclusion', 1),
(119, 'MNCU', 'copper mine(s)', 'a mine where copper ore is extracted', 1),
(120, 'MFGCU', 'copper works', 'a facility for processing copper ore', 1),
(121, 'RFC', 'coral reef(s)', 'a surface-navigation hazard composed of coral', 1),
(122, 'CRRL', 'corral(s)', 'a pen or enclosure for confining or capturing animals', 1),
(123, 'CRDR', 'corridor', 'a strip or area of land having significance as an access way', 1),
(124, 'ESTC', 'cotton plantation', 'an estate specializing in the cultivation of cotton', 1),
(125, 'HSEC', 'country house', 'a large house, mansion, or chateau, on a large estate', 1),
(126, 'CTHSE', 'courthouse', 'a building in which courts of law are held', 1),
(127, 'COVE', 'cove(s)', 'a small coastal indentation, smaller than a bay', 1),
(128, 'LKC', 'crater lake', 'a lake in a crater or caldera', 1),
(129, 'LKSC', 'crater lakes', 'lakes in a crater or caldera', 1),
(130, 'CRTR', 'crater(s)', 'a generally circular saucer or bowl-shaped depression caused by volcanic or meteorite explosive action', 1),
(131, 'CUET', 'cuesta(s)', 'an asymmetric ridge formed on tilted strata', 1),
(132, 'CULT', 'cultivated area', 'an area under cultivation', 1),
(133, 'CRNT', 'current', 'a horizontal flow of water in a given direction with uniform velocity', 1),
(134, 'CSTM', 'customs house', 'a building in a port where customs and duties are paid, and where vessels are entered and cleared', 1),
(135, 'PSTC', 'customs post', 'a building at an international boundary where customs and duties are paid on goods', 1),
(136, 'CUTF', 'cutoff', 'a channel formed as a result of a stream cutting through a meander neck', 1),
(137, 'DARY', 'dairy', 'a facility for the processing, sale and distribution of milk or milk products', 1),
(138, 'DAM', 'dam', 'a barrier constructed across a stream to impound water', 1),
(139, 'DEPU', 'deep', 'a localized deep area within the confines of a larger feature, such as a trough, basin or trench', 1),
(140, 'DLTA', 'delta', 'a flat plain formed by alluvial deposits at the mouth of a stream', 1),
(141, 'PCLD', 'dependent political entity', 'dependent political entity', 1),
(142, 'DPR', 'depression(s)', 'a low area surrounded by higher land and usually characterized by interior drainage', 1),
(143, 'DSRT', 'desert', 'a large area with little or no vegetation due to extreme environmental conditions', 1),
(144, 'PPLW', 'destroyed populated place', 'a village, town or city destroyed by a natural disaster, or by war', 1),
(145, 'MNDT', 'diatomite mine(s)', 'a place where diatomaceous earth is extracted', 1),
(146, 'DIKE', 'dike', 'an earth or stone embankment usually constructed for flood or stream control', 1),
(147, 'DIP', 'diplomatic facility', 'office, residence, or facility of a foreign government, which may include an embassy, consulate, chancery, office of charge d’affaires, or other diplomatic, economic, military, or cultural mission', 1),
(148, 'HSPD', 'dispensary', 'a building where medical or dental aid is dispensed', 1),
(149, 'STMD', 'distributary(-ies)', 'a branch which flows away from the main stream, as in a delta or irrigation canal', 1),
(150, 'DTCH', 'ditch', 'a small artificial watercourse dug for draining or irrigating the land', 1),
(151, 'DTCHM', 'ditch mouth(s)', 'an area where a drainage ditch enters a lagoon, lake or bay', 1),
(152, 'DVD', 'divide', 'a line separating adjacent drainage basins', 1),
(153, 'DCK', 'dock(s)', 'a waterway between two piers, or cut into the land for the berthing of ships', 1),
(154, 'DCKB', 'docking basin', 'a part of a harbor where ships dock', 1),
(155, 'DCKY', 'dockyard', 'a facility for servicing, building, or repairing ships', 1),
(156, 'BSND', 'drainage basin', 'an area drained by a stream', 1),
(157, 'CNLD', 'drainage canal', 'an artificial waterway carrying water away from a wetland or from drainage ditches', 1),
(158, 'DTCHD', 'drainage ditch', 'a ditch which serves to drain the land', 1),
(159, 'DCKD', 'dry dock', 'a dock providing support for a vessel, and means for removing the water so that the bottom of the vessel can be exposed', 1),
(160, 'SBED', 'dry stream bed', 'a channel formerly containing the water of a stream', 1),
(161, 'DUNE', 'dune(s)', 'a wave form, ridge or star shape feature composed of sand', 1),
(162, 'RGNE', 'economic region', 'a region of a country established for economic development or for statistical purposes', 1),
(163, 'SCRP', 'escarpment', 'a long line of cliffs or steep slopes separating level surfaces above and below', 1),
(164, 'EST', 'estate(s)', 'a large commercialized agricultural landholding with associated buildings and other facilities', 1),
(165, 'ESTY', 'estuary', 'a funnel-shaped stream mouth or embayment where fresh water mixes with sea water under tidal influences', 1),
(166, 'STNE', 'experiment station', 'a facility for carrying out experiments', 1),
(167, 'FCL', 'facility', 'a building or buildings housing a center, institute, foundation, hospital, prison, mission, courthouse, etc.', 1),
(168, 'CTRF', 'facility center', 'a place where more than one facility is situated', 1),
(169, 'MFG', 'factory', 'one or more buildings where goods are manufactured, processed or fabricated', 1),
(170, 'FAN', 'fan(s)', 'a fan-shaped wedge of coarse alluvium with apex merging with a mountain stream bed and the fan spreading out at a low angle slope onto an adjacent plain', 1),
(171, 'FRM', 'farm', 'a tract of land with associated buildings devoted to agriculture', 1),
(172, 'PPLF', 'farm village', 'a populated place where the population is largely engaged in agricultural activities', 1),
(173, 'FRMS', 'farms', 'tracts of land with associated buildings devoted to agriculture', 1),
(174, 'FRMT', 'farmstead', 'the buildings and adjacent service areas of a farm', 1),
(175, 'FY', 'ferry', 'a boat or other floating conveyance and terminal facilities regularly used to transport people and vehicles across a waterbody', 1),
(176, 'FYT', 'ferry terminal', 'a place where ferries pick-up and discharge passengers, vehicles and or cargo', 1),
(177, 'FLD', 'field(s)', 'an open as opposed to wooded area', 1),
(178, 'FIRE', 'fire station', 'building housing firefighters and/or fire fighting equipment', 1),
(179, 'ADM1', 'first-order administrative division', 'a primary administrative division of a country, such as a state in the United States', 1),
(180, 'FISH', 'fishing area', 'a fishing ground, bank or area where fishermen go to catch fish', 1),
(181, 'PNDSF', 'fishponds', 'ponds or enclosures in which fish are kept or raised', 1),
(182, 'FSR', 'fissure', 'a crack associated with volcanism', 1),
(183, 'FJD', 'fjord', 'a long, narrow, steep-walled, deep-water arm of the sea at high latitudes, usually along mountainous coasts', 1),
(184, 'FJDS', 'fjords', 'long, narrow, steep-walled, deep-water arms of the sea at high latitudes, usually along mountainous coasts', 1),
(185, 'FORD', 'ford', 'a shallow part of a stream which can be crossed on foot or by land vehicle', 1),
(186, 'RESF', 'forest reserve', 'a forested area set aside for preservation or controlled use', 1),
(187, 'STNF', 'forest station', 'a collection of buildings and facilities for carrying out forest management', 1),
(188, 'FRST', 'forest(s)', 'an area dominated by tree vegetation', 1),
(189, 'INLTQ', 'former inlet', 'an inlet which has been filled in, or blocked by deposits', 1),
(190, 'MLSGQ', 'former sugar mill', 'a sugar mill no longer used as a sugar mill', 1),
(191, 'FT', 'fort', 'a defensive structure or earthworks', 1),
(192, 'FRSTF', 'fossilized forest', 'a forest fossilized by geologic processes and now exposed at the earth''s surface', 1),
(193, 'FNDY', 'foundry', 'a building or works where metal casting is carried out', 1),
(194, 'ADM4', 'fourth-order administrative division', 'a subdivision of a third-order administrative division', 1),
(195, 'ZNF', 'free trade zone', 'an area, usually a section of a port, where goods may be received and shipped free of customs duty and of most customs regulations', 1),
(196, 'PCLF', 'freely associated state', 'freely associated state', 1),
(197, 'DPOF', 'fuel depot', 'an area where fuel is stored', 1),
(198, 'GAP', 'gap', 'a low place in a ridge, not used for transportation', 1),
(199, 'GDN', 'garden(s)', 'an enclosure for displaying selected plant or animal life', 1),
(200, 'GOSP', 'gas-oil separator plant', 'a facility for separating gas from oil', 1),
(201, 'GASF', 'gasfield', 'an area containing a subterranean store of natural gas of economic value', 1),
(202, 'GATE', 'gate', 'a controlled access entrance or exit', 1),
(203, 'GYSR', 'geyser', 'a type of hot spring with intermittent eruptions of jets of hot water and steam', 1),
(204, 'GHAT', 'ghāt', 'a set of steps leading to a river, which are of religious significance, and at their base is usually a platform for bathing', 1),
(205, 'GLCR', 'glacier(s)', 'a mass of ice, usually at high latitudes or high elevations, with sufficient thickness to flow away from the source area in lobes, tongues, or masses', 1),
(206, 'MNAU', 'gold mine(s)', 'a mine where gold ore, or alluvial gold is extracted', 1),
(207, 'RECG', 'golf course', 'a recreation field where golf is played', 1),
(208, 'GRGE', 'gorge(s)', 'a short, narrow, steep-sided section of a stream valley', 1),
(209, 'GRSLD', 'grassland', 'an area dominated by grass vegetation', 1),
(210, 'GRVE', 'grave', 'a burial site', 1),
(211, 'GVL', 'gravel area', 'an area covered with gravel', 1),
(212, 'GRAZ', 'grazing area', 'an area of grasses and shrubs used for grazing', 1),
(213, 'GHSE', 'guest house', 'a house used to provide lodging for paying guests', 1),
(214, 'GULF', 'gulf', 'a large recess in the coastline, larger than a bay', 1),
(215, 'HLT', 'halting place', 'a place where caravans stop for rest', 1),
(216, 'HMCK', 'hammock(s)', 'a patch of ground, distinct from and slightly above the surrounding plain or wetland. Often occurs in groups', 1),
(217, 'AIRG', 'hangar', 'a covered and usually enclosed area for housing and repairing aircraft', 1),
(218, 'VALG', 'hanging valley', 'a valley the floor of which is notably higher than the valley or shore to which it leads; most common in areas that have been glaciated', 1),
(219, 'HBR', 'harbor(s)', 'a haven or space of deep water so sheltered by the adjacent land as to afford a safe anchorage for ships', 1),
(220, 'HDLD', 'headland', 'a high projection of land extending into a large body of water beyond the line of the coast', 1),
(221, 'STMH', 'headwaters', 'the source and upper part of a stream, including the upper drainage basin', 1),
(222, 'HTH', 'heath', 'an upland moor or sandy area dominated by low shrubby vegetation including heather', 1),
(223, 'AIRH', 'heliport', 'a place where helicopters land and take off', 1),
(224, 'HERM', 'hermitage', 'a secluded residence, usually for religious sects', 1),
(225, 'HLL', 'hill', 'a rounded elevation of limited extent rising above the surrounding land with local relief of less than 300m', 1),
(226, 'HLLS', 'hills', 'rounded elevations of limited extent rising above the surrounding land with local relief of less than 300m', 1),
(227, 'ADMDH', 'historical administrative division', 'a former administrative division of a political entity, undifferentiated as to administrative level', 1),
(228, 'ADM1H', 'historical first-order administrative division', 'a former first-order administrative division', 1),
(229, 'ADM4H', 'historical fourth-order administrative division', 'a former fourth-order administrative division', 1),
(230, 'PCLH', 'historical political entity', 'a former political entity', 1),
(231, 'PPLH', 'historical populated place', 'a populated place that no longer exists', 1),
(232, 'RRH', 'historical railroad', 'a former permanent twin steel-rail track on which freight and passenger cars move long distances', 1),
(233, 'RSTNH', 'historical railroad station', 'a former facility comprising ticket office, platforms, etc. for loading and unloading train passengers and freight', 1),
(234, 'RGNH', 'historical region', 'a former area distinguished by one or more observable physical or cultural characteristics', 1),
(235, 'ADM2H', 'historical second-order administrative division', 'a former second-order administrative division', 1),
(236, 'HSTS', 'historical site', 'a place of historical importance', 1),
(237, 'ADM3H', 'historical third-order administrative division', 'a former third-order administrative division', 1),
(238, 'UFHU', 'historical undersea feature', 'an undersea feature whose existence has been subsequently disproved', 1),
(239, 'HMSD', 'homestead', 'a residence, owner''s or manager''s, on a sheep or cattle station, woolshed, outcamp, or Aboriginal outstation, specific to Australia and New Zealand', 1),
(240, 'HSP', 'hospital', 'a building in which sick or injured, especially those confined to bed, are medically treated', 1),
(241, 'SPNT', 'hot spring(s)', 'a place where hot ground water flows naturally out of the ground', 1),
(242, 'HTL', 'hotel', 'a building providing lodging and/or meals for the public', 1),
(243, 'HSE', 'house(s)', 'a building used as a human habitation', 1),
(244, 'DEVH', 'housing development', 'a tract of land on which many houses of similar design are built according to a development plan', 1),
(245, 'RESH', 'hunting reserve', 'a tract of land used primarily for hunting', 1),
(246, 'HUT', 'hut', 'a small primitive house', 1),
(247, 'HUTS', 'huts', 'small primitive houses', 1),
(248, 'PSH', 'hydroelectric power station', 'a building where electricity is generated from water power', 1),
(249, 'CAPG', 'icecap', 'a dome-shaped mass of glacial ice covering an area of mountain summits or other high lands; smaller than an ice sheet', 1),
(250, 'DPRG', 'icecap depression', 'a comparatively depressed area on an icecap', 1),
(251, 'DOMG', 'icecap dome', 'a comparatively elevated area on an icecap', 1),
(252, 'RDGG', 'icecap ridge', 'a linear elevation on an icecap', 1),
(253, 'PCLI', 'independent political entity', 'independent political entity', 1),
(254, 'INDS', 'industrial area', 'an area characterized by industrial activity', 1),
(255, 'INLT', 'inlet', 'a narrow waterway extending into the land, or connecting a bay or lagoon with a larger body of water', 1),
(256, 'STNI', 'inspection station', 'a station at which vehicles, goods, and people are inspected', 1),
(257, 'TRGD', 'interdune trough(s)', 'a long wind-swept trough between parallel longitudinal dunes', 1),
(258, 'INTF', 'interfluve', 'a relatively undissected upland between adjacent stream valleys', 1),
(259, 'LKI', 'intermittent lake', 'intermittent lake', 1),
(260, 'LKSI', 'intermittent lakes', 'intermittent lakes', 1),
(261, 'LKOI', 'intermittent oxbow lake', 'intermittent oxbow lake', 1),
(262, 'PNDI', 'intermittent pond', 'intermittent pond', 1),
(263, 'PNDSI', 'intermittent ponds', 'intermittent ponds', 1),
(264, 'POOLI', 'intermittent pool', 'intermittent pool', 1),
(265, 'RSVI', 'intermittent reservoir', 'intermittent reservoir', 1),
(266, 'LKNI', 'intermittent salt lake', 'intermittent salt lake', 1),
(267, 'LKSNI', 'intermittent salt lakes', 'intermittent salt lakes', 1),
(268, 'PNDNI', 'intermittent salt pond(s)', 'intermittent salt pond(s)', 1),
(269, 'STMI', 'intermittent stream', 'intermittent stream', 1),
(270, 'WTLDI', 'intermittent wetland', 'intermittent wetland', 1),
(271, 'RDIN', 'intersection', 'a junction of two or more highways by a system of separate levels that permit traffic to pass from one to another without the crossing of traffic streams', 1),
(272, 'MNFE', 'iron mine(s)', 'a mine where iron ore is extracted', 1),
(273, 'FLDI', 'irrigated field(s)', 'a tract of level or terraced land which is irrigated', 1),
(274, 'CNLI', 'irrigation canal', 'a canal which serves as a main conduit for irrigation water', 1),
(275, 'DTCHI', 'irrigation ditch', 'a ditch which serves to distribute irrigation water', 1),
(276, 'SYSI', 'irrigation system', 'a network of ditches and one or more of the following elements: water supply, reservoir, canal, pump, well, drain, etc.', 1),
(277, 'ISL', 'island', 'a tract of land, smaller than a continent, surrounded by water at high water', 1),
(278, 'ISLS', 'islands', 'tracts of land, smaller than a continent, surrounded by water at high water', 1),
(279, 'STLMT', 'Israeli settlement', 'Israeli settlement', 1),
(280, 'ISTH', 'isthmus', 'a narrow strip of land connecting two larger land masses and bordered by water', 1),
(281, 'JTY', 'jetty', 'a structure built out into the water at a river mouth or harbor entrance to regulate currents and silting', 1),
(282, 'KRST', 'karst area', 'a distinctive landscape developed on soluble rock such as limestone characterized by sinkholes, caves, disappearing streams, and underground drainage', 1),
(283, 'CMPLA', 'labor camp', 'a camp used by migrant or temporary laborers', 1),
(284, 'LGN', 'lagoon', 'a shallow coastal waterbody, completely or partly separated from a larger body of water by a barrier island, coral reef or other depositional feature', 1),
(285, 'LGNS', 'lagoons', 'shallow coastal waterbodies, completely or partly separated from a larger body of water by a barrier island, coral reef or other depositional feature', 1),
(286, 'LK', 'lake', 'a large inland body of standing water', 1),
(287, 'LBED', 'lake bed(s)', 'a dried up or drained area of a former lake', 1),
(288, 'CHNL', 'lake channel(s)', 'that part of a lake having water deep enough for navigation between islands, shoals, etc.', 1),
(289, 'RGNL', 'lake region', 'a tract of land distinguished by numerous lakes', 1),
(290, 'LKS', 'lakes', 'large inland bodies of standing water', 1),
(291, 'ISLT', 'land-tied island', 'a coastal island connected to the mainland by barrier beaches, levees or dikes', 1),
(292, 'LNDF', 'landfill', 'a place for trash and garbage disposal in which the waste is buried between layers of earth to build up low-lying land', 1),
(293, 'LDNG', 'landing', 'a place where boats receive or discharge passengers and freight, but lacking most port facilities', 1),
(294, 'LAVA', 'lava area', 'an area of solidified lava', 1),
(295, 'MNPB', 'lead mine(s)', 'a mine where lead ore is extracted', 1),
(296, 'LTER', 'leased area', 'a tract of land leased by the United Kingdom from the People''s Republic of China to form part of Hong Kong', 1),
(297, 'LEPC', 'leper colony', 'a settled area inhabited by lepers in relative isolation', 1),
(298, 'HSPL', 'leprosarium', 'an asylum or hospital for lepers', 1),
(299, 'LEV', 'levee', 'a natural low embankment bordering a distributary or meandering stream; often built up artificially to control floods', 1),
(300, 'LTHSE', 'lighthouse', 'a distinctive structure exhibiting a major navigation light', 1),
(301, 'MFGLM', 'limekiln', 'a furnace in which limestone is reduced to lime', 1),
(302, 'GOVL', 'local government office', 'a facility housing local governmental offices, usually a city, town, or village hall', 1),
(303, 'LCTY', 'locality', 'a minor area or place of unspecified or mixed character and indefinite boundaries', 1),
(304, 'LOCK', 'lock(s)', 'a basin in a waterway with gates at each end by means of which vessels are passed from one water level to another', 1),
(305, 'CMPL', 'logging camp', 'a camp used by loggers', 1),
(306, 'STMSB', 'lost river', 'a surface stream that disappears into an underground channel, or dries up in an arid area', 1),
(307, 'MVA', 'maneuver area', 'a tract of land where military field exercises are carried out', 1),
(308, 'ISLM', 'mangrove island', 'a mangrove swamp surrounded by a waterbody', 1),
(309, 'MGV', 'mangrove swamp', 'a tropical tidal mud flat characterized by mangrove vegetation', 1),
(310, 'MAR', 'marina', 'a harbor facility for small boats, yachts, etc.', 1),
(311, 'CHNM', 'marine channel', 'that part of a body of water deep enough for navigation through an area otherwise not suitable', 1),
(312, 'SCHN', 'maritime school', 'a school at which maritime sciences form the core of the curriculum', 1),
(313, 'MKT', 'market', 'a place where goods are bought and sold at regular intervals', 1),
(314, 'MRSH', 'marsh(es)', 'a wetland dominated by grass-like vegetation', 1),
(315, 'MDW', 'meadow', 'a small, poorly drained area dominated by grassy vegetation', 1),
(316, 'NKM', 'meander neck', 'a narrow strip of land between the two limbs of a meander loop at its narrowest point', 1),
(317, 'CTRM', 'medical center', 'a complex of health care buildings including two or more of the following: hospital, medical school, clinic, pharmacy, doctor''s offices, etc.', 1),
(318, 'MESA', 'mesa(s)', 'a flat-topped, isolated elevation with steep slopes on all sides, less extensive than a plateau', 1),
(319, 'STNM', 'meteorological station', 'a station at which weather elements are recorded', 1),
(320, 'MILB', 'military base', 'a place used by an army or other armed service for storing arms and supplies, and for accommodating and training troops, a base from which operations can be initiated', 1),
(321, 'INSM', 'military installation', 'a facility for use of and control by armed forces', 1),
(322, 'SCHM', 'military school', 'a school at which military science forms the core of the curriculum', 1),
(323, 'ML', 'mill(s)', 'a building housing machines for transforming, shaping, finishing, grinding, or extracting products', 1),
(324, 'MN', 'mine(s)', 'a site where mineral ores are extracted from the ground by excavating surface pits and subterranean passages', 1),
(325, 'MNA', 'mining area', 'an area of mine sites where minerals and ores are extracted', 1),
(326, 'CMPMN', 'mining camp', 'a camp used by miners', 1),
(327, 'MSSN', 'mission', 'a place characterized by dwellings, school, church, hospital and other facilities operated by a religious group for the purpose of providing charitable services and to propagate religion', 1),
(328, 'MOLE', 'mole', 'a massive structure of masonry or large stones serving as a pier or breakwater', 1),
(329, 'MSTY', 'monastery', 'a building and grounds where a community of monks lives in seclusion', 1),
(330, 'MNMT', 'monument', 'a commemorative structure or statue', 1),
(331, 'MOOR', 'moor(s)', 'an area of open ground overlaid with wet peaty soils', 1),
(332, 'MRN', 'moraine', 'a mound, ridge, or other accumulation of glacial till', 1),
(333, 'MSQE', 'mosque', 'a building for public Islamic worship', 1),
(334, 'MND', 'mound(s)', 'a low, isolated, rounded hill', 1),
(335, 'MT', 'mountain', 'an elevation standing high above the surrounding area with small summit area, steep slopes and local relief of 300m or more', 1),
(336, 'MTS', 'mountains', 'a mountain range or a group of mountains or high ridges', 1),
(337, 'FLTM', 'mud flat(s)', 'a relatively level area of mud either between high and low tide lines, or subject to flooding', 1),
(338, 'MFGM', 'munitions plant', 'a factory where ammunition is made', 1),
(339, 'MUS', 'museum', 'a building where objects of permanent interest in one or more of the arts and sciences are preserved and exhibited', 1),
(340, 'NRWS', 'narrows', 'a navigable narrow part of a bay, strait, river, etc.', 1),
(341, 'TNLN', 'natural tunnel', 'a cave that is open at both ends', 1),
(342, 'RESN', 'nature reserve', 'an area reserved for the maintenance of a natural habitat', 1),
(343, 'NVB', 'naval base', 'an area used to store supplies, provide barracks for troops and naval personnel, a port for naval vessels, and from which operations are initiated', 1),
(344, 'CNLN', 'navigation canal(s)', 'a watercourse constructed for navigation of vessels', 1),
(345, 'CHNN', 'navigation channel', 'a buoyed channel of sufficient depth for the safe navigation of vessels', 1),
(346, 'MNNI', 'nickel mine(s)', 'a mine where nickel ore is extracted', 1),
(347, 'NOV', 'novitiate', 'a religious house or school where novices are trained', 1),
(348, 'PSN', 'nuclear power station', 'nuclear power station', 1),
(349, 'NTK', 'nunatak', 'a rock or mountain peak protruding through glacial ice', 1),
(350, 'NTKS', 'nunataks', 'rocks or mountain peaks protruding through glacial ice', 1),
(351, 'NSY', 'nursery(-ies)', 'a place where plants are propagated for transplanting or grafting', 1),
(352, 'OAS', 'oasis(-es)', 'an area in a desert made productive by the availability of water', 1),
(353, 'OBPT', 'observation point', 'a wildlife or scenic observation point', 1),
(354, 'OBS', 'observatory', 'a facility equipped for observation of atmospheric or space phenomena', 1),
(355, 'OCN', 'ocean', 'one of the major divisions of the vast expanse of salt water covering part of the earth', 1),
(356, 'BLDO', 'office building', 'commercial building where business and/or services are conducted', 1),
(357, 'CMPO', 'oil camp', 'a camp used by oilfield workers', 1),
(358, 'ESTO', 'oil palm plantation', 'an estate specializing in the cultivation of oil palm trees', 1),
(359, 'OILP', 'oil pipeline', 'a pipeline used for transporting oil', 1),
(360, 'OILJ', 'oil pipeline junction', 'a section of an oil pipeline where two or more pipes join together', 1),
(361, 'TRMO', 'oil pipeline terminal', 'a tank farm or loading facility at the end of an oil pipeline', 1),
(362, 'PMPO', 'oil pumping station', 'a facility for pumping oil through a pipeline', 1),
(363, 'OILR', 'oil refinery', 'a facility for converting crude oil into refined petroleum products', 1),
(364, 'OILW', 'oil well', 'a well from which oil may be pumped', 1),
(365, 'OILF', 'oilfield', 'an area containing a subterranean store of petroleum of economic value', 1),
(366, 'GRVO', 'olive grove', 'a planting of olive trees', 1),
(367, 'MLO', 'olive oil mill', 'a mill where oil is extracted from olives', 1),
(368, 'OCH', 'orchard(s)', 'a planting of fruit or nut trees', 1),
(369, 'MLM', 'ore treatment plant', 'a facility for improving the metal content of ore by concentration', 1),
(370, 'OVF', 'overfalls', 'an area of breaking waves caused by the meeting of currents or by waves moving against the current', 1),
(371, 'LKO', 'oxbow lake', 'a crescent-shaped lake commonly found adjacent to meandering streams', 1),
(372, 'PGDA', 'pagoda', 'a tower-like storied structure, usually a Buddhist shrine', 1),
(373, 'PAL', 'palace', 'a large stately house, often a royal or presidential residence', 1),
(374, 'GRVP', 'palm grove', 'a planting of palm trees', 1),
(375, 'RESP', 'palm tree reserve', 'an area of palm trees where use is controlled', 1),
(376, 'PAN', 'pan', 'a near-level shallow, natural depression or basin, usually containing an intermittent lake, pond, or pool', 1),
(377, 'PANS', 'pans', 'a near-level shallow, natural depression or basin, usually containing an intermittent lake, pond, or pool', 1),
(378, 'PRSH', 'parish', 'an ecclesiastical district', 1),
(379, 'PRK', 'park', 'an area, often of forested land, maintained as a place of beauty, or for recreation', 1),
(380, 'PRKGT', 'park gate', 'a controlled access to a park', 1),
(381, 'PRKHQ', 'park headquarters', 'a park administrative facility', 1),
(382, 'GARG', 'parking garage', 'a building or underground facility used exclusively for parking vehicles', 1),
(383, 'PKLT', 'parking lot', 'an area used for parking vehicles', 1),
(384, 'PASS', 'pass', 'a break in a mountain range or other high obstruction, used for transportation from one side to the other [See also gap]', 1),
(385, 'PSTP', 'patrol post', 'a post from which patrols are sent out', 1),
(386, 'PK', 'peak', 'a pointed elevation atop a mountain, ridge, or other hypsographic feature', 1),
(387, 'PKS', 'peaks', 'pointed elevations atop a mountain, ridge, or other hypsographic features', 1),
(388, 'PEAT', 'peat cutting area', 'an area where peat is harvested', 1),
(389, 'PEN', 'peninsula', 'an elongate area of land projecting into a body of water and nearly surrounded by water', 1),
(390, 'BSNP', 'petroleum basin', 'an area underlain by an oil-rich structural basin', 1),
(391, 'MFGPH', 'phosphate works', 'a facility for producing fertilizer', 1),
(392, 'PIER', 'pier', 'a structure built out into navigable water on piles providing berthing for ships and recreation', 1),
(393, 'GRVPN', 'pine grove', 'a planting of pine trees', 1),
(394, 'MNPL', 'placer mine(s)', 'a place where heavy metals are concentrated and running water is used to extract them from unconsolidated sediments', 1),
(395, 'PLN', 'plain(s)', 'an extensive area of comparatively level to gently undulating land, lacking surface irregularities, and usually adjacent to a higher area', 1),
(396, 'PLAT', 'plateau', 'an elevated plain with steep slopes on one or more sides, and often with incised streams', 1),
(397, 'PT', 'point', 'a tapering piece of land projecting into a body of water, less prominent than a cape', 1),
(398, 'PTS', 'points', 'tapering pieces of land projecting into a body of water, less prominent than a cape', 1),
(399, 'PLDR', 'polder', 'an area reclaimed from the sea by diking and draining', 1),
(400, 'PP', 'police post', 'a building in which police are stationed', 1),
(401, 'PCL', 'political entity', 'political entity', 1),
(402, 'PND', 'pond', 'a small standing waterbody', 1),
(403, 'PNDS', 'ponds', 'small standing waterbodies', 1),
(404, 'POOL', 'pool(s)', 'a small and comparatively still, deep part of a larger body of water such as a stream or harbor; or a small body of standing water', 1),
(405, 'PPLL', 'populated locality', 'an area similar to a locality but with a small group of dwellings or other buildings', 1),
(406, 'PPL', 'populated place', 'a city, town, village, or other agglomeration of buildings where people live and work', 1),
(407, 'PPLS', 'populated places', 'cities, towns, villages, or other agglomerations of buildings where people live and work', 1),
(408, 'PRT', 'port', 'a place provided with terminal and transfer facilities for loading and discharging waterborne cargo or passengers, usually located in a harbor', 1),
(409, 'PTGE', 'portage', 'a place where boats, goods, etc., are carried overland between navigable waters', 1),
(410, 'PO', 'post office', 'a public building in which mail is received, sorted and distributed', 1),
(411, 'PS', 'power station', 'a facility for generating electric power', 1),
(412, 'PRN', 'prison', 'a facility for confining prisoners', 1),
(413, 'PRMN', 'promenade', 'a place for public walking, usually along a beach front', 1),
(414, 'PROM', 'promontory(-ies)', 'a bluff or prominent hill overlooking or projecting into a lowland', 1),
(415, 'PYR', 'pyramid', 'an ancient massive structure of square ground plan with four triangular faces meeting at a point and used for enclosing tombs', 1),
(416, 'PYRS', 'pyramids', 'ancient massive structures of square ground plan with four triangular faces meeting at a point and used for enclosing tombs', 1),
(417, 'MNQR', 'quarry(-ies)', 'a surface mine where building stone or gravel and sand, etc. are extracted', 1),
(418, 'QUAY', 'quay', 'a structure of solid construction along a shore or bank which provides berthing for ships and which generally provides cargo handling facilities', 1),
(419, 'QCKS', 'quicksand', 'an area where loose sand with water moving through it may become unstable when heavy objects are placed at the surface, causing them to sink', 1),
(420, 'RECR', 'racetrack', 'a track where races are held', 1),
(421, 'OBSR', 'radio observatory', 'a facility equipped with an array of antennae for receiving radio waves from space', 1),
(422, 'STNR', 'radio station', 'a facility for producing and transmitting information by radio waves', 1),
(423, 'RR', 'railroad', 'a permanent twin steel-rail track on which freight and passenger cars move long distances', 1),
(424, 'RJCT', 'railroad junction', 'a place where two or more railroad tracks join', 1),
(425, 'RSD', 'railroad siding', 'a short track parallel to and joining the main track', 1),
(426, 'RSGNL', 'railroad signal', 'a signal at the entrance of a particular section of track governing the movement of trains', 1),
(427, 'RSTN', 'railroad station', 'a facility comprising ticket office, platforms, etc. for loading and unloading train passengers and freight', 1),
(428, 'RSTP', 'railroad stop', 'a place lacking station facilities where trains stop to pick up and unload passengers and freight', 1),
(429, 'TNLRR', 'railroad tunnel', 'a tunnel through which a railroad passes', 1),
(430, 'RYD', 'railroad yard', 'a system of tracks used for the making up of trains, and switching and storing freight cars', 1),
(431, 'RNCH', 'ranch(es)', 'a large farm specializing in extensive grazing of livestock', 1),
(432, 'RPDS', 'rapids', 'a turbulent section of a stream associated with a steep, irregular stream bed', 1),
(433, 'RVN', 'ravine(s)', 'a small, narrow, deep, steep-sided stream channel, smaller than a gorge', 1),
(434, 'RCH', 'reach', 'a straight section of a navigable stream or channel between two bends', 1),
(435, 'RF', 'reef(s)', 'a surface-navigation hazard composed of consolidated material', 1),
(436, 'PRNJ', 'reformatory', 'a facility for confining, training, and reforming young law offenders', 1),
(437, 'CMPRF', 'refugee camp', 'a camp used by refugees', 1),
(438, 'RGN', 'region', 'an area distinguished by one or more observable physical or cultural characteristics', 1),
(439, 'CTRR', 'religious center', 'a facility where more than one religious activity is carried out, e.g., retreat, school, monastery, worship', 1),
(440, 'PPLR', 'religious populated place', 'a populated place whose population is largely engaged in religious occupations', 1),
(441, 'RLG', 'religious site', 'an ancient site of significant religious importance', 1),
(442, 'ITTR', 'research institute', 'a facility where research is carried out', 1),
(443, 'RESV', 'reservation', 'a tract of land set aside for aboriginal, tribal, or native populations', 1),
(444, 'RES', 'reserve', 'a tract of public land reserved for future use or restricted as to use', 1),
(445, 'RSV', 'reservoir(s)', 'an artificial pond or lake', 1),
(446, 'RSRT', 'resort', 'a specialized facility for vacation, health, or participation sports activities', 1),
(447, 'RHSE', 'resthouse', 'a structure maintained for the rest and shelter of travelers', 1),
(448, 'RLGR', 'retreat', 'a place of temporary seclusion, especially for religious groups', 1),
(449, 'RDGE', 'ridge(s)', 'a long narrow elevation with steep sides, and a more or less continuous crest', 1),
(450, 'RD', 'road', 'an open way with improved surface for transportation of animals, people and vehicles', 1),
(451, 'RDB', 'road bend', 'a conspicuously curved or bent section of a road', 1),
(452, 'RDCUT', 'road cut', 'an excavation cut through a hill or ridge for a road', 1),
(453, 'RDJCT', 'road junction', 'a place where two or more roads join', 1),
(454, 'TNLRD', 'road tunnel', 'a tunnel through which a road passes', 1),
(455, 'RDST', 'roadstead', 'an open anchorage affording less protection than a harbor', 1),
(456, 'RK', 'rock', 'a conspicuous, isolated rocky mass', 1),
(457, 'HMDA', 'rock desert', 'a relatively sand-free, high bedrock plateau in a hot desert, with or without a gravel veneer', 1),
(458, 'RKFL', 'rockfall', 'an irregular mass of fallen rock at the base of a cliff or steep slope', 1),
(459, 'RKS', 'rocks', 'conspicuous, isolated rocky masses', 1),
(460, 'RKRY', 'rookery', 'a breeding place of a colony of birds or seals', 1),
(461, 'ESTR', 'rubber plantation', 'an estate which specializes in growing and tapping rubber trees', 1),
(462, 'RUIN', 'ruin(s)', 'a destroyed or decayed structure which is no longer functional', 1),
(463, 'BDGQ', 'ruined bridge', 'a destroyed or decayed bridge which is no longer functional', 1),
(464, 'DAMQ', 'ruined dam', 'a destroyed or decayed dam which is no longer functional', 1),
(465, 'SBKH', 'sabkha(s)', 'a salt flat or salt encrusted plain subject to periodic inundation from flooding or high tides', 1),
(466, 'SDL', 'saddle', 'a broad, open pass crossing a ridge or between hills or mountains', 1),
(467, 'SALT', 'salt area', 'a shallow basin or flat where salt accumulates after periodic inundation', 1),
(468, 'MFGN', 'salt evaporation ponds', 'diked salt ponds used in the production of solar evaporated salt', 1),
(469, 'LKN', 'salt lake', 'an inland body of salt water with no outlet', 1),
(470, 'LKSN', 'salt lakes', 'inland bodies of salt water with no outlet', 1),
(471, 'MRSHN', 'salt marsh', 'a flat area, subject to periodic salt water inundation, dominated by grassy salt-tolerant plants', 1),
(472, 'MNN', 'salt mine(s)', 'a mine from which salt is extracted', 1),
(473, 'PNDN', 'salt pond', 'a small standing body of salt water often in a marsh or swamp, usually along a seacoast', 1),
(474, 'PNDSN', 'salt ponds', 'small standing bodies of salt water often in a marsh or swamp, usually along a seacoast', 1),
(475, 'SNTR', 'sanatorium', 'a facility where victims of physical or mental disorders are treated', 1),
(476, 'SAND', 'sand area', 'a tract of land covered with sand', 1),
(477, 'ERG', 'sandy desert', 'an extensive tract of shifting sand and sand dunes', 1),
(478, 'STNS', 'satellite station', 'a facility for tracking and communicating with orbiting satellites', 1),
(479, 'MLSW', 'sawmill', 'a mill where logs or lumber are sawn to specified shapes and sizes', 1),
(480, 'SCH', 'school', 'building(s) where instruction in one or more branches of knowledge takes place', 1),
(481, 'ADMS', 'school district', 'school district', 1),
(482, 'STNB', 'scientific research base', 'a scientific facility used as a base from which research is carried out or monitored', 1),
(483, 'SCRB', 'scrubland', 'an area of low trees, bushes, and shrubs stunted by some environmental limitation', 1),
(484, 'SEA', 'sea', 'a large body of salt water more or less confined by continuous land or chains of islands forming a subdivision of an ocean', 1),
(485, 'SCNU', 'seachannel', 'a continuously sloping, elongated depression commonly found in fans or plains and customarily bordered by levees on one or two sides', 1),
(486, 'SCSU', 'seachannels', 'continuously sloping, elongated depressions commonly found in fans or plains and customarily bordered by levees on one or two sides', 1),
(487, 'SMU', 'seamount', 'an elevation rising generally more than 1,000 meters and of limited extent across the summit', 1),
(488, 'SMSU', 'seamounts', 'elevations rising generally more than 1,000 meters and of limited extent across the summit', 1),
(489, 'AIRS', 'seaplane landing area', 'a place on a waterbody where floatplanes land and take off', 1),
(490, 'PPLA', 'seat of a first-order administrative division', 'seat of a first-order administrative division (PPLC takes precedence over PPLA)', 1),
(491, 'PPLA4', 'seat of a fourth-order administrative division', 'seat of a fourth-order administrative division', 1),
(492, 'PPLA2', 'seat of a second-order administrative division', 'seat of a second-order administrative division', 1),
(493, 'PPLA3', 'seat of a third-order administrative division', 'seat of a third-order administrative division', 1);
INSERT INTO `LocationType` (`id`, `Code`, `Name`, `Description`, `lang_id`) VALUES
(494, 'ADM2', 'second-order administrative division', 'a subdivision of a first-order administrative division', 1),
(495, 'BNKX', 'section of bank', 'section of bank', 1),
(496, 'CNLX', 'section of canal', 'section of canal', 1),
(497, 'ESTX', 'section of estate', 'section of estate', 1),
(498, 'HBRX', 'section of harbor', 'section of harbor', 1),
(499, 'PCLIX', 'section of independent political entity', 'section of independent political entity', 1),
(500, 'STMIX', 'section of intermittent stream', 'section of intermittent stream', 1),
(501, 'ISLX', 'section of island', 'section of island', 1),
(502, 'LGNX', 'section of lagoon', 'section of lagoon', 1),
(503, 'LKX', 'section of lake', 'section of lake', 1),
(504, 'PENX', 'section of peninsula', 'section of peninsula', 1),
(505, 'PLNX', 'section of plain', 'section of plain', 1),
(506, 'PLATX', 'section of plateau', 'section of plateau', 1),
(507, 'PPLX', 'section of populated place', 'section of populated place', 1),
(508, 'RFX', 'section of reef', 'section of reef', 1),
(509, 'STMX', 'section of stream', 'section of stream', 1),
(510, 'VALX', 'section of valley', 'section of valley', 1),
(511, 'WADX', 'section of wadi', 'section of wadi', 1),
(512, 'FLLSX', 'section of waterfall(s)', 'section of waterfall(s)', 1),
(513, 'PCLS', 'semi-independent political entity', 'semi-independent political entity', 1),
(514, 'SWT', 'sewage treatment plant', 'facility for the processing of sewage and/or wastewater', 1),
(515, 'SHPF', 'sheepfold', 'a fence or wall enclosure for sheep and other small herd animals', 1),
(516, 'SHOL', 'shoal(s)', 'a surface-navigation hazard composed of unconsolidated material', 1),
(517, 'SHOPC', 'shopping center or mall', 'an urban shopping area featuring a variety of shops surrounding a usually open-air concourse reserved for pedestrian traffic; or a large suburban building or group of buildings containing various shops with associated passageways', 1),
(518, 'SHOR', 'shore', 'a narrow zone bordering a waterbody which covers and uncovers at high and low water, respectively', 1),
(519, 'SHRN', 'shrine', 'a structure or place memorializing a person or religious concept', 1),
(520, 'SILL', 'sill', 'the low part of a gap or saddle separating basins', 1),
(521, 'SINK', 'sinkhole', 'a small crater-shape depression in a karst area', 1),
(522, 'ESTSL', 'sisal plantation', 'an estate that specializes in growing sisal', 1),
(523, 'SLID', 'slide', 'a mound of earth material, at the base of a slope and the associated scoured area', 1),
(524, 'SLP', 'slope(s)', 'a surface with a relatively uniform slope angle', 1),
(525, 'SLCE', 'sluice', 'a conduit or passage for carrying off surplus water from a waterbody, usually regulated by means of a sluice gate', 1),
(526, 'SNOW', 'snowfield', 'an area of permanent snow and ice forming the accumulation area of a glacier', 1),
(527, 'SD', 'sound', 'a long arm of the sea forming a channel between the mainland and an island or islands; or connecting two larger bodies of water', 1),
(528, 'SPA', 'spa', 'a resort area usually developed around a medicinal spring', 1),
(529, 'CTRS', 'space center', 'a facility for launching, tracking, or controlling satellites and space vehicles', 1),
(530, 'SPLY', 'spillway', 'a passage or outlet through which surplus water flows over, around or through a dam', 1),
(531, 'SPIT', 'spit', 'a narrow, straight or curved continuation of a beach into a waterbody', 1),
(532, 'SPNG', 'spring(s)', 'a place where ground water flows naturally out of the ground', 1),
(533, 'SPUR', 'spur(s)', 'a subordinate ridge projecting outward from a hill, mountain or other elevation', 1),
(534, 'SQR', 'square', 'a broad, open, public area near the center of a town or city', 1),
(535, 'STBL', 'stable', 'a building for the shelter and feeding of farm animals, especially horses', 1),
(536, 'STDM', 'stadium', 'a structure with an enclosure for athletic games with tiers of seats for spectators', 1),
(537, 'STPS', 'steps', 'stones or slabs placed for ease in ascending or descending a steep slope', 1),
(538, 'STKR', 'stock route', 'a route taken by livestock herds', 1),
(539, 'REG', 'stony desert', 'a desert plain characterized by a surface veneer of gravel and stones', 1),
(540, 'RET', 'store', 'a building where goods and/or services are offered for sale', 1),
(541, 'SHSE', 'storehouse', 'a building for storing goods, especially provisions', 1),
(542, 'STRT', 'strait', 'a relatively narrow waterway, usually narrower and less extensive than a sound, connecting two larger bodies of water', 1),
(543, 'STM', 'stream', 'a body of running water moving to a lower level in a channel on land', 1),
(544, 'BNKR', 'stream bank', 'a sloping margin of a stream channel which normally confines the stream to its channel on land', 1),
(545, 'STMB', 'stream bend', 'a conspicuously curved or bent segment of a stream', 1),
(546, 'STMGS', 'stream gauging station', 'named place where a measuring station for a watercourse, reservoir or other water body exists', 1),
(547, 'STMM', 'stream mouth(s)', 'a place where a stream discharges into a lagoon, lake, or the sea', 1),
(548, 'STMS', 'streams', 'bodies of running water moving to a lower level in a channel on land', 1),
(549, 'ST', 'street', 'a paved urban thoroughfare', 1),
(550, 'DAMSB', 'sub-surface dam', 'a dam put down to bedrock in a sand river', 1),
(551, 'SUBW', 'subway', 'a railroad used for mass public transportation primarily in urban areas, all or part of the system may be located below, above, or at ground level', 1),
(552, 'SUBS', 'subway station', 'a facility comprising ticket office, platforms, etc. for loading and unloading subway passengers', 1),
(553, 'MLSG', 'sugar mill', 'a facility where sugar cane is processed into raw sugar', 1),
(554, 'ESTSG', 'sugar plantation', 'an estate that specializes in growing sugar cane', 1),
(555, 'MFGSG', 'sugar refinery', 'a facility for converting raw sugar into refined sugar', 1),
(556, 'SPNS', 'sulphur spring(s)', 'a place where sulphur ground water flows naturally out of the ground', 1),
(557, 'SWMP', 'swamp', 'a wetland dominated by tree vegetation', 1),
(558, 'SYG', 'synagogue', 'a place for Jewish worship and religious instruction', 1),
(559, 'TMTU', 'tablemount (or guyot)', 'a seamount having a comparatively smooth, flat top', 1),
(560, 'TMSU', 'tablemounts (or guyots)', 'seamounts having a comparatively smooth, flat top', 1),
(561, 'TAL', 'talus slope', 'a steep concave slope formed by an accumulation of loose rock fragments at the base of a cliff or steep slope', 1),
(562, 'OILT', 'tank farm', 'a tract of land occupied by large, cylindrical, metal tanks in which oil or liquid petrochemicals are stored', 1),
(563, 'ESTT', 'tea plantation', 'an estate which specializes in growing tea bushes', 1),
(564, 'SCHT', 'technical school', 'post-secondary school with a specifically technical or vocational curriculum', 1),
(565, 'TMPL', 'temple(s)', 'an edifice dedicated to religious worship', 1),
(566, 'AIRT', 'terminal', 'airport facilities for the handling of freight and passengers', 1),
(567, 'TRR', 'terrace', 'a long, narrow alluvial platform bounded by steeper slopes above and below, usually overlooking a waterbody', 1),
(568, 'TERR', 'territory', 'territory', 1),
(569, 'ADM3', 'third-order administrative division', 'a subdivision of a second-order administrative division', 1),
(570, 'CRKT', 'tidal creek(s)', 'a meandering channel in a coastal wetland subject to bi-directional tidal currents', 1),
(571, 'FLTT', 'tidal flat(s)', 'a large flat area of mud or sand attached to the shore and alternately covered and uncovered by the tide', 1),
(572, 'MNSN', 'tin mine(s)', 'a mine where tin ore is extracted', 1),
(573, 'TOLL', 'toll gate/barrier', 'highway toll collection station', 1),
(574, 'TMB', 'tomb(s)', 'a structure for interring bodies', 1),
(575, 'TOWR', 'tower', 'a high conspicuous structure, typically much higher than its diameter', 1),
(576, 'RDCR', 'traffic circle', 'a road junction formed around a central circle about which traffic moves in one direction only', 1),
(577, 'TRL', 'trail', 'a path, track, or route used by pedestrians, animals, or off-road vehicles', 1),
(578, 'TRANT', 'transit terminal', 'facilities for the handling of vehicular freight and passengers', 1),
(579, 'TREE', 'tree(s)', 'a conspicuous tree used as a landmark', 1),
(580, 'TRIG', 'triangulation station', 'a point on the earth whose position has been determined by triangulation', 1),
(581, 'TRB', 'tribal area', 'a tract of land used by nomadic or other tribes', 1),
(582, 'TUND', 'tundra', 'a marshy, treeless, high latitude plain, dominated by mosses, lichens, and low shrub vegetation under permafrost conditions', 1),
(583, 'TNL', 'tunnel', 'a subterranean passageway for transportation', 1),
(584, 'TNLS', 'tunnels', 'subterranean passageways for transportation', 1),
(585, 'CNLSB', 'underground irrigation canal(s)', 'a gently inclined underground tunnel bringing water for irrigation from aquifers', 1),
(586, 'LKSB', 'underground lake', 'a standing body of water in a cave', 1),
(587, 'APNU', 'undersea apron', 'a gentle slope, with a generally smooth surface, particularly found around groups of islands and seamounts', 1),
(588, 'ARCU', 'undersea arch', 'a low bulge around the southeastern end of the island of Hawaii', 1),
(589, 'ARRU', 'undersea arrugado', 'an area of subdued corrugations off Baja California', 1),
(590, 'BNKU', 'undersea bank', 'an elevation, typically located on a shelf, over which the depth of water is relatively shallow but sufficient for safe surface navigation', 1),
(591, 'BKSU', 'undersea banks', 'elevations, typically located on a shelf, over which the depth of water is relatively shallow but sufficient for safe surface navigation', 1),
(592, 'BSNU', 'undersea basin', 'a depression more or less equidimensional in plan and of variable extent', 1),
(593, 'BNCU', 'undersea bench', 'a small terrace', 1),
(594, 'BDLU', 'undersea borderland', 'a region adjacent to a continent, normally occupied by or bordering a shelf, that is highly irregular with depths well in excess of those typical of a shelf', 1),
(595, 'CNYU', 'undersea canyon', 'a relatively narrow, deep depression with steep sides, the bottom of which generally has a continuous slope', 1),
(596, 'CNSU', 'undersea canyons', 'relatively narrow, deep depressions with steep sides, the bottom of which generally has a continuous slope', 1),
(597, 'CDAU', 'undersea cordillera', 'an entire mountain system including the subordinate ranges, interior plateaus, and basins', 1),
(598, 'ESCU', 'undersea escarpment (or scarp)', 'an elongated and comparatively steep slope separating flat or gently sloping areas', 1),
(599, 'FANU', 'undersea fan', 'a relatively smooth feature normally sloping away from the lower termination of a canyon or canyon system', 1),
(600, 'FLTU', 'undersea flat', 'a small level or nearly level area', 1),
(601, 'FRKU', 'undersea fork', 'a branch of a canyon or valley', 1),
(602, 'FRSU', 'undersea forks', 'a branch of a canyon or valley', 1),
(603, 'FRZU', 'undersea fracture zone', 'an extensive linear zone of irregular topography of the sea floor, characterized by steep-sided or asymmetrical ridges, troughs, or escarpments', 1),
(604, 'FURU', 'undersea furrow', 'a closed, linear, narrow, shallow depression', 1),
(605, 'GAPU', 'undersea gap', 'a narrow break in a ridge or rise', 1),
(606, 'GLYU', 'undersea gully', 'a small valley-like feature', 1),
(607, 'HLLU', 'undersea hill', 'an elevation rising generally less than 500 meters', 1),
(608, 'HLSU', 'undersea hills', 'elevations rising generally less than 500 meters', 1),
(609, 'HOLU', 'undersea hole', 'a small depression of the sea floor', 1),
(610, 'KNLU', 'undersea knoll', 'an elevation rising generally more than 500 meters and less than 1,000 meters and of limited extent across the summit', 1),
(611, 'KNSU', 'undersea knolls', 'elevations rising generally more than 500 meters and less than 1,000 meters and of limited extent across the summits', 1),
(612, 'LDGU', 'undersea ledge', 'a rocky projection or outcrop, commonly linear and near shore', 1),
(613, 'LEVU', 'undersea levee', 'an embankment bordering a canyon, valley, or seachannel', 1),
(614, 'MDVU', 'undersea median valley', 'the axial depression of the mid-oceanic ridge system', 1),
(615, 'MESU', 'undersea mesa', 'an isolated, extensive, flat-topped elevation on the shelf, with relatively steep sides', 1),
(616, 'MOTU', 'undersea moat', 'an annular depression that may not be continuous, located at the base of many seamounts, islands, and other isolated elevations', 1),
(617, 'MNDU', 'undersea mound', 'a low, isolated, rounded hill', 1),
(618, 'MTU', 'undersea mountain', 'a well-delineated subdivision of a large and complex positive feature', 1),
(619, 'MTSU', 'undersea mountains', 'well-delineated subdivisions of a large and complex positive feature', 1),
(620, 'PKU', 'undersea peak', 'a prominent elevation, part of a larger feature, either pointed or of very limited extent across the summit', 1),
(621, 'PKSU', 'undersea peaks', 'prominent elevations, part of a larger feature, either pointed or of very limited extent across the summit', 1),
(622, 'PNLU', 'undersea pinnacle', 'a high tower or spire-shaped pillar of rock or coral, alone or cresting a summit', 1),
(623, 'PLNU', 'undersea plain', 'a flat, gently sloping or nearly level region', 1),
(624, 'PLTU', 'undersea plateau', 'a comparatively flat-topped feature of considerable extent, dropping off abruptly on one or more sides', 1),
(625, 'PLFU', 'undersea platform', 'a flat or gently sloping underwater surface extending seaward from the shore', 1),
(626, 'PRVU', 'undersea province', 'a region identifiable by a group of similar physiographic features whose characteristics are markedly in contrast with surrounding areas', 1),
(627, 'RMPU', 'undersea ramp', 'a gentle slope connecting areas of different elevations', 1),
(628, 'RNGU', 'undersea range', 'a series of associated ridges or seamounts', 1),
(629, 'RAVU', 'undersea ravine', 'a small canyon', 1),
(630, 'RFU', 'undersea reef', 'a surface-navigation hazard composed of consolidated material', 1),
(631, 'RFSU', 'undersea reefs', 'surface-navigation hazards composed of consolidated material', 1),
(632, 'RDGU', 'undersea ridge', 'a long narrow elevation with steep sides', 1),
(633, 'RDSU', 'undersea ridges', 'long narrow elevations with steep sides', 1),
(634, 'RISU', 'undersea rise', 'a broad elevation that rises gently, and generally smoothly, from the sea floor', 1),
(635, 'SDLU', 'undersea saddle', 'a low part, resembling in shape a saddle, in a ridge or between contiguous seamounts', 1),
(636, 'SHFU', 'undersea shelf', 'a zone adjacent to a continent (or around an island) that extends from the low water line to a depth at which there is usually a marked increase of slope towards oceanic depths', 1),
(637, 'EDGU', 'undersea shelf edge', 'a line along which there is a marked increase of slope at the outer margin of a continental shelf or island shelf', 1),
(638, 'SHVU', 'undersea shelf valley', 'a valley on the shelf, generally the shoreward extension of a canyon', 1),
(639, 'SHLU', 'undersea shoal', 'a surface-navigation hazard composed of unconsolidated material', 1),
(640, 'SHSU', 'undersea shoals', 'hazards to surface navigation composed of unconsolidated material', 1),
(641, 'SILU', 'undersea sill', 'the low part of an underwater gap or saddle separating basins, including a similar feature at the mouth of a fjord', 1),
(642, 'SLPU', 'undersea slope', 'the slope seaward from the shelf edge to the beginning of a continental rise or the point where there is a general reduction in slope', 1),
(643, 'SPRU', 'undersea spur', 'a subordinate elevation, ridge, or rise projecting outward from a larger feature', 1),
(644, 'TERU', 'undersea terrace', 'a relatively flat horizontal or gently inclined surface, sometimes long and narrow, which is bounded by a steeper ascending slope on one side and by a steep descending slope on the opposite side', 1),
(645, 'TNGU', 'undersea tongue', 'an elongate (tongue-like) extension of a flat sea floor into an adjacent higher feature', 1),
(646, 'TRNU', 'undersea trench', 'a long, narrow, characteristically very deep and asymmetrical depression of the sea floor, with relatively steep sides', 1),
(647, 'TRGU', 'undersea trough', 'a long depression of the sea floor characteristically flat bottomed and steep sided, and normally shallower than a trench', 1),
(648, 'VALU', 'undersea valley', 'a relatively shallow, wide depression, the bottom of which usually has a continuous gradient', 1),
(649, 'VLSU', 'undersea valleys', 'a relatively shallow, wide depression, the bottom of which usually has a continuous gradient', 1),
(650, 'USGE', 'United States Government Establishment', 'a facility operated by the United States Government in Panama', 1),
(651, 'UPLD', 'upland', 'an extensive interior region of high land with low to moderate surface relief', 1),
(652, 'VAL', 'valley', 'an elongated depression usually traversed by a stream', 1),
(653, 'VALS', 'valleys', 'elongated depressions usually traversed by a stream', 1),
(654, 'VETF', 'veterinary facility', 'a building or camp at which veterinary services are available', 1),
(655, 'VIN', 'vineyard', 'a planting of grapevines', 1),
(656, 'VINS', 'vineyards', 'plantings of grapevines', 1),
(657, 'VLC', 'volcano', 'a conical elevation composed of volcanic materials with a crater at the top', 1),
(658, 'WAD', 'wadi', 'a valley or ravine, bounded by relatively steep banks, which in the rainy season becomes a watercourse; found primarily in North Africa and the Middle East', 1),
(659, 'WADB', 'wadi bend', 'a conspicuously curved or bent segment of a wadi', 1),
(660, 'WADJ', 'wadi junction', 'a place where two or more wadies join', 1),
(661, 'WADM', 'wadi mouth', 'the lower terminus of a wadi where it widens into an adjoining floodplain, depression, or waterbody', 1),
(662, 'WADS', 'wadies', 'valleys or ravines, bounded by relatively steep banks, which in the rainy season become watercourses; found primarily in North Africa and the Middle East', 1),
(663, 'WALL', 'wall', 'a thick masonry structure, usually enclosing a field or building, or forming the side of a structure', 1),
(664, 'MLWTR', 'water mill', 'a mill powered by running water', 1),
(665, 'PMPW', 'water pumping station', 'a facility for pumping water from a major well or through a pipeline', 1),
(666, 'RSVT', 'water tank', 'a contained pool or tank of water at, below, or above ground level', 1),
(667, 'WTRC', 'watercourse', 'a natural, well-defined channel produced by flowing water, or an artificial channel designed to carry flowing water', 1),
(668, 'FLLS', 'waterfall(s)', 'a perpendicular or very steep descent of the water of a stream', 1),
(669, 'WTRH', 'waterhole(s)', 'a natural hole, hollow, or small depression that contains water, used by man and animals, especially in arid areas', 1),
(670, 'WTRW', 'waterworks', 'a facility for supplying potable water through a water source and a system of pumps and filtration beds', 1),
(671, 'WEIR', 'weir(s)', 'a small dam in a stream, designed to raise the water level or to divert stream flow through a desired channel', 1),
(672, 'WLL', 'well', 'a cylindrical hole, pit, or tunnel drilled or dug down to a depth from which water, oil, or gas can be pumped or brought to the surface', 1),
(673, 'WLLS', 'wells', 'cylindrical holes, pits, or tunnels drilled or dug down to a depth from which water, oil, or gas can be pumped or brought to the surface', 1),
(674, 'WTLD', 'wetland', 'an area subject to inundation, usually characterized by bog, marsh, or swamp vegetation', 1),
(675, 'STNW', 'whaling station', 'a facility for butchering whales and processing train oil', 1),
(676, 'WHRF', 'wharf(-ves)', 'a structure of open rather than solid construction along a shore or a bank which provides berthing for ships and cargo-handling facilities', 1),
(677, 'WHRL', 'whirlpool', 'a turbulent, rotating movement of water in a stream', 1),
(678, 'RESW', 'wildlife reserve', 'a tract of public land reserved for the preservation of wildlife', 1),
(679, 'MLWND', 'windmill', 'a mill or water pump powered by wind', 1),
(680, 'WRCK', 'wreck', 'the site of the remains of a wrecked vessel', 1),
(681, 'ZN', 'zone', 'zone', 1),
(682, 'ZOO', 'zoo', 'a zoological garden or park where wild animals are kept for exhibition', 1);